### PR TITLE
JordanAdair#47-CodingSheetsPage

### PR DESCRIPTION
**Pull request by JordanAdair**
Added the ability to complete tasks, and a dynamic progress bar.

### CODE REVIEW

**Comment by JordanAdair** [comment]
Just noticed that my "Prettier" extension shifted the spacing around a lot. I can turn off this plugin if this makes it difficult to review my code, or if you just don't like the way it's formatting things.

**Comment by Nayaker** [comment]
@JordanAdair I have reviewed the code, no issues with the spacing because my prettier would revert it back in my environment.

Code this very nicely written, clean and understandable. 

Good stuff! 🚀

**Comment by JordanAdair** [comment]
> 

Alright, I starred it.

I've completed a few courses on Redux on Codecademy, but have never implemented it in an actual project. Are you looking to use Redux on this project?

**Comment by Nayaker** [comment]
I am interested in using Redux on this project. While I am not an expert in Redux, I am eager to learn and improve my skills by working on this project. I will begin my work on Redux after January 15th, and I welcome the opportunity for you to contribute and collaborate with me at that time. This will be a valuable learning experience for both of us. 

I will tag you when I start :)

**Comment by JordanAdair** [comment]
Sure, sounds like fun. 
If you need me for anything in the meantime let me know.

**Comment by Nayaker** [comment]
Hey @JordanAdair, check this one out https://github.com/Nayaker/Algorithmist/issues/54

**Pull request merged**
