### PR TITLE
Issue#35 solved - If registration not started coding competitions

### PR DESCRIPTION
**Pull request by adrianmarinwork**
Issue#35 solved - If registration not started coding competitions

If I have made a mistake or forgot something just tell me!

### CODE REVIEW

**Comment by Nayaker** [comment]
Outstanding! Great work done ✨

Just one suggestion - when you are raising a PR try to send only those files which you want to be added to the code, for example here, in this case, package-lock and yarn were not required. Those were creating some issues which merging.  

Again, amazing code, would love to work again with you. Happy coding. 🚀

**Comment by Nayaker** [comment]
@adrianmarinwork I have also added you on the landing page - 

Screenshot 2022-12-03 at 1 37 34 AM

**Comment by adrianmarinwork** [comment]
You are right, my bad by adding those files to the pull request, I'll keep it mind next time!
Thank you! Your project looks pretty cool I like it, if you have any issue that you want me to take care don't doubt to call me.

**Comment by Nayaker** [comment]
Check your email, I have mailed something up there.

**Pull request merged**
