### PR TITLE
updated readme

### LINKED ISSUE #12: Update the ReadMe file
Write the readme file for the project by whatever you understand about the project (https://algorithmist-dev.web.app/) in case of anything that you don't understand you can ask it here. Don't worry about the correctness of whatever you write, if will be reviewed and changed. 

I want the structure to be something similar to this : 
Screenshot 2022-11-19 at 11 50 50 AM <br/>

Screenshot 2022-11-19 at 11 51 11 AM

### PR DESCRIPTION
**Pull request by ThePlugJumbo**
fixed #12.  I added a preview of the website, and some new sections & text.

### CODE REVIEW

**Comment by Nayaker** [comment]
Good work! But I think a few more things can be added here, like a table explaining all the pages. It's good for now but if you can update it, even more, that would be great 🚀. 

But really @ThePlugJumbo Amazing work, happy coding!

**Comment by ThePlugJumbo** [comment]
No problem, can you assign me to this one and I will keep adding to it 👍

**Comment by Nayaker** [comment]
Great I will create a new issue about <b>Update Readme</b> and give specific details about the task. If possible do give me your email address or WhatsApp number, it is easier to communicate that way.

**Comment by ThePlugJumbo** [comment]
Sure, chnxcx@gmail.com is the best way to reach me.

**Pull request merged**
